logging:
  level: debug
  encoding: logfmt
hosts:
  resolvers:
    - type: string
    - type: static
      config: ./examples/config/global-query-static-resolver-example-config-devcontainer.yaml
querier:
  type: api
  max_concurrent: 64
  config: ./examples/config/global-query-api-client-querier-example-config-devcontainer.yaml
server:
  addr: localhost:8146
