name: Build Docker Images

on:
  push:
   tags:
     - 'v*.*.*'

jobs:
  build-docker:
    runs-on: ubuntu-latest
    environment: prod
    steps:

      - name: Set environment
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "SEM_VER=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: goprobe
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push sensor image
        uses: docker/build-push-action@v6
        with:
          push: true
          target: sensor
          tags: goprobe/sensor:${{ env.COMMIT_SHA }},goprobe/sensor:${{ env.RELEASE_VERSION }},goprobe/sensor:latest

      - name: Build and push query image
        uses: docker/build-push-action@v6
        with:
          push: true
          target: query
          tags: goprobe/query:${{ env.COMMIT_SHA }},goprobe/query:${{ env.RELEASE_VERSION }},goprobe/query:latest
